#!/usr/bin/env python3
"""Bounded read-only analysis of the frozen v3 S7 AM42 failure; no retuning."""
from pathlib import Path
import json,xml.etree.ElementTree as ET,collections
ROOT=Path(__file__).resolve().parents[1];RUN='high_pressure_S7_am_42_v3';REF='high_pressure_S0_am_42_v3';NODE='432452987'
def read(p):return json.loads((ROOT/p).read_text())
m=read(f'runs/{RUN}/manifest.json');ref=read(f'runs/{REF}/manifest.json');assert m['network_hash']==ref['network_hash'] and m['demand_hash']==ref['demand_hash']
scene=read(f'runs/{RUN}/network.json');snap=read(f'runs/{RUN}/long_wait_snapshots.json');final=snap['snapshots'][-1];heads=[v for v in final['vehicles'] if not v['leader'] and v['road'].startswith(':'+NODE+'_')]
assert len(heads)==5
links={int(v['lane'].split('_')[-2]):v['id'] for v in heads}
net=ET.parse(ROOT/'networks/joined_north_surface_v3/network.net.xml').getroot();j=next(j for j in net.findall('junction') if j.get('id')==NODE);req={int(q.get('index')):q for q in j.findall('request')}
relations=[]
for i,vid in sorted(links.items()):relations.append({'link_index':i,'vehicle_id':vid,'potential_yield_to_occupied_links':[k for k in links if req[i].get('response')[::-1][k]=='1'],'geometric_foes_among_occupied_links':[k for k in links if req[i].get('foes')[::-1][k]=='1']})
signals=[v for v in read(f'runs/{RUN}/signals.json') if v['tls']==NODE];late=[v for v in signals if v['time']>=3300];events=[v for v in read(f'runs/{RUN}/events.json') if v.get('tls')==NODE];extensions=[v for v in events if v['type']=='green_extension'];incident=[e for e in scene['edges'] if e['from_node']==NODE or e['to_node']==NODE];assert min(e['length'] for e in incident)>30
source=ET.parse(ROOT/'data/raw/yulin.osm').getroot();osmn=next(n for n in source.findall('node') if n.get('id')==NODE)
summary={'scenario':RUN,'reference':REF,'network_variant':'joined_north_surface_v3','network_hash':m['network_hash'],'same_demand_hash':m['demand_hash'],'s7_final_state':read(f'runs/{RUN}/timeseries.json')[-1],'s0_final_state':read(f'runs/{REF}/timeseries.json')[-1],'primary_persistent_block_junction':{'id':NODE,'location':'倪家桥路 × 玉林街/玉林南街','wgs84_lon_lat':[float(osmn.get('lon')),float(osmn.get('lat'))],'source_tags':{t.get('k'):t.get('v') for t in osmn.findall('tag')},'source_node_url':f'https://www.openstreetmap.org/node/{NODE}','sumo_type':j.get('type'),'source_ways':sorted({e['osm_way_id'] for e in incident}),'incident_edges':[{'id':e['id'],'name':e['name'],'length_m':e['length'],'source_tags':e['osm_tags'],'source_url':f'https://www.openstreetmap.org/way/{e["osm_way_id"]}'} for e in incident],'earliest_continuous_wait_start_estimate_s':min(final['time']-v['wait'] for v in heads),'heads':heads,'potential_response_relations':relations},'late_signal_observations':{'window':[3300,4200],'state_change_records':len(late),'state_counts':dict(collections.Counter(x['state'] for x in late)),'last_states':late[-12:]},'s7_controller_events':{'extensions_total':len(extensions),'last_extensions':extensions[-8:]},'mechanism_supported':'Five stopped vehicles occupy conflicting internal links of a single surface junction while upstream queues persist. Signals continue alternating green/yellow/all-red. The S7 extension guard only tests outgoing-lane occupancy; it continues reporting downstream_space=True while the internal intersection is blocked. This supports policy-condition-sensitive simulated internal-junction gridlock/spillback and exposes an incomplete receiving-space check.','mechanism_not_established':['Static response relations indicate potential reciprocal yielding, not a measured per-vehicle causal graph. No saved-state deletion intervention was run for this final S7 case.','Same-network S0 drainage establishes outcome sensitivity to control/trajectory evolution, not real-world inevitability or proof that SUMO conflict handling is fully realistic.','No new 0.20m external-edge split was found at this primary lock junction; nearby incident external segments are38.77–177.88m. No evidence here justifies another automatic junction merge.','Secondary late stalled heads near node8013476765 are retained in snapshots; this bounded review does not claim all809 vehicles share one independently proved causal chain.'],'decision':'Keep frozen v3 and negative S7 outcome. No network mutation, vehicle removal, teleporting, policy retuning or extra capacity introduced. Controller redesign/field calibration require a separate study.','code_reference':'src/traffic_twin/policies.py PolicyController.step:receiving uses getLastStepOccupancy(outgoing), not internal via-lane occupancy.'}
(ROOT/'docs/evidence/s7_am_residual_diagnostic.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2));print(json.dumps({'heads':len(heads),'late_signal_state_changes':len(late),'earliest_persistent_wait_start':summary['primary_persistent_block_junction']['earliest_continuous_wait_start_estimate_s'],'source_node_tags':summary['primary_persistent_block_junction']['source_tags']},ensure_ascii=False))
